---
- name: Deploy Ketchup Container
  hosts: "gitlab-runner"
  gather_facts: True

  vars:
    CONTAINER_NAME: 'ketchup'
    IMAGE_NAME: 'ketchup'
    IMAGE_PATH: 'test/{{ IMAGE_NAME }}'
    IMAGE_VER: 0.1

  environment:
    http_proxy: "http://proxy.jpn.hp.com:8080"
    https_proxy: "http://proxy.jpn.hp.com:8080"

  tasks:
    - name: Cleanup running conatainer
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        state: absent
      tags: absent

    - name: Create ketchup container
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ IMAGE_PATH }}:{{ IMAGE_VER }}"
        state: started
        expose:
          - 80
      tags: started
