---
stages:
 - build
 - test
 - review
# - deploy

variables:
  CONTAINER_IMAGE: c7-systemd
  CONTAINER_IMAGE_PATH: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CONTAINER_IMAGE}

pkg_build:
  stage: build
  script:
   - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
   - docker build . -t ${CONTAINER_IMAGE_PATH}
   - docker push ${CONTAINER_IMAGE_PATH}
  tags:
   - docker

ketchup_test:
  stage: test
  variables:
    CONTAINER_NAME: "ketchup"
    RUNNER_HOST_IP: "10.0.50.31"
    CONTAINER_PORT: 8080

  before_script:
   - docker rm -f ${CONTAINER_NAME} ||true
  script:
   - docker run --detach --privileged --name ${CONTAINER_NAME} -p ${CONTAINER_PORT}:${CONTAINER_PORT} ${CONTAINER_IMAGE_PATH} /sbin/init
   - docker exec ${CONTAINER_NAME} /bin/bash -c "ansible-playbook -i ./tests/inventory ./${CONTAINER_NAME}.yml --syntax-check"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "ansible-playbook -i ./tests/inventory -l ${CONTAINER_NAME} ./${CONTAINER_NAME}.yml"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "cd ./tests; ansible-playbook -i ./inventory ./${CONTAINER_NAME}_test.yml --syntax-check"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "cd ./tests; ansible-playbook -i ./inventory ./${CONTAINER_NAME}_test.yml -vv"
"
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    url: http://${RUNNER_HOST_IP}:${CONTAINER_PORT}/admin
    on_stop: review_stop
#  after_script:
#   - docker rm -f ${CONTAINER_NAME}
#   - docker rmi -f ${CONTAINER_IMAGE_PATH}
  tags:
   - docker

ketchup_nginx_test:
  stage: test
  variables:
    CONTAINER_NAME: "ketchup_nginx"
  script:
   - docker run --detach --privileged --name ${CONTAINER_NAME} -p 80:80 ${CONTAINER_IMAGE_PATH} /sbin/init
   - docker exec ${CONTAINER_NAME} /bin/bash -c "ansible-playbook -i ./tests/inventory ./ketchup.yml --syntax-check"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "ansible-playbook -i ./tests/inventory -l ${CONTAINER_NAME} ./ketchup.yml"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "cd ./tests; ansible-playbook -i ./inventory ./${CONTAINER_NAME}_test.yml --syntax-check"
   - docker exec ${CONTAINER_NAME} /bin/bash -c "cd ./tests; ansible-playbook -i ./inventory ./${CONTAINER_NAME}_test.yml -vv"
  after_script:
   - docker rm -f ${CONTAINER_NAME}
  tags:
   - docker

review_stop:
  stage: review
  variables:
    GIT_STRATEGY: none
    CONTAINER_NAME: "ketchup"
  script:
    - docker rm -f ${CONTAINER_NAME}
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop
  tags:
   - docker
