---
- name: Install Ngnix frontend for Ketchup
  hosts: "ketchup_nginx"
  gather_facts: True
  roles:
    - role: repos_el
      when: 'ansible_os_family == "RedHat"'

    - role: packages_el
      packages_el_nginx_packages: True
      when: 'ansible_os_family == "RedHat"'

    - role: nginx
