---
- name: include task specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths: '../vars'

- block:
  - name: Check status for repo files
    wait_for:
      path: '/etc/yum.repos.d/{{ item }}'
      timeout: 5
    with_items: '{{ yum_online_repo_files }}'

#  - name: Check contents for repo files
#    copy:
#      src: '{{ item }}'
#      dest: '/etc/yum.repos.d/{{ item }}'
#    with_items: '{{ yum_online_repo_files }}'
#    check_mode: true
#    diff: true
#    register: test_repo_files
#    when: "use_epel_repo|bool == 0"
#
#  - name: Check difference from repo files
#    assert:
#      that:
#        - "item.changed != 1"
#      msg: "{{ item.diff.0.after_header }} and {{ item.diff.0.before_header }} are not identical"
#    with_items: "{{ test_repo_files.results }}"

  - name: Gathaering registered repos
    command: yum repolist
    args:
      warn: no
    register: test_registered_repos

  - name: Check registration for epel repo
    assert:
      that:
        - "'epel' in test_registered_repos.stdout"
        - "'nginx' not in test_registered_repos.stdout"
      msg: "epel repo is not enabled"
    when: 'use_epel_repo|bool'

  - name: Check registration for nginx repo
    assert:
      that:
        - "'epel' not in test_registered_repos.stdout"
        - "'nginx' in test_registered_repos.stdout"
      msg: "nginx repo is not enabled"
    when: 'use_epel_repo|bool == 0'

  become: True
